import type { Meeting } from "../common/model";

export const DEMO_MCGILL_MEETINGS: Meeting[] = [
  {
    id: "demo-mcgill-comp202-lec",
    institutionId: "mcgill",
    courseCode: "COMP 202",
    nativeSection: "001",
    nativeComponentType: "LEC",
    courseName: "Foundations of Programming",
    termLabel: "Fall 2026",
    days: ["MO", "WE"],
    startTime: "10:05",
    endTime: "11:25",
    startDate: "2026-09-02",
    endDate: "2026-12-02",
    location: {
      kind: "physical",
      nativeText: "LEA 132",
      buildingId: "leacock-building",
      room: "132",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-30T12:00:00.000Z" },
  },
  {
    id: "demo-mcgill-chem110-lec",
    institutionId: "mcgill",
    courseCode: "CHEM 110",
    nativeSection: "001",
    nativeComponentType: "LEC",
    courseName: "General Chemistry 1",
    termLabel: "Fall 2026",
    days: ["TU", "TH"],
    startTime: "11:35",
    endTime: "12:55",
    startDate: "2026-09-03",
    endDate: "2026-12-03",
    location: {
      kind: "physical",
      nativeText: "MAASS 112",
      buildingId: "otto-maass-chemistry-building",
      room: "112",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-30T12:00:00.000Z" },
  },
  {
    id: "demo-mcgill-phys101-lec",
    institutionId: "mcgill",
    courseCode: "PHYS 101",
    nativeSection: "001",
    nativeComponentType: "LEC",
    courseName: "Introductory Physics",
    termLabel: "Fall 2026",
    days: ["MO", "WE"],
    startTime: "14:35",
    endTime: "15:55",
    startDate: "2026-09-02",
    endDate: "2026-12-02",
    location: {
      kind: "physical",
      nativeText: "RPHYS 114",
      buildingId: "rutherford-physics-building",
      room: "114",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-30T12:00:00.000Z" },
  },
];
