import { createUniversityDemoSchedule } from "../common/demo-generator";
import type { Meeting } from "../common/model";

export const DEMO_WATERLOO_MEETINGS: Meeting[] = createUniversityDemoSchedule("waterloo", [
  {
    courseCode: "MATH 135",
    courseName: "Algebra for Honours Mathematics",
    nativeSection: "001",
    nativeComponentType: "LEC",
    days: ["MO", "WE", "FR"],
    startTime: "09:30",
    endTime: "10:20",
    nativeText: "MC 2066",
    buildingId: "mathematics-computer-building",
    room: "2066",
  },
  {
    courseCode: "CS 135",
    courseName: "Designing Functional Programs",
    nativeSection: "002",
    nativeComponentType: "LEC",
    days: ["MO", "WE", "FR"],
    startTime: "11:30",
    endTime: "12:20",
    nativeText: "DC 1351",
    buildingId: "william-g-davis-computer-research-centre",
    room: "1351",
  },
  {
    courseCode: "MATH 135",
    courseName: "Algebra Tutorial",
    nativeSection: "T01",
    nativeComponentType: "TUT",
    days: ["TU"],
    startTime: "10:30",
    endTime: "11:20",
    nativeText: "MC 4020",
    buildingId: "mathematics-computer-building",
    room: "4020",
  },
  {
    courseCode: "PSYCH 101",
    courseName: "Introductory Psychology",
    nativeSection: "003",
    nativeComponentType: "LEC",
    days: ["TU", "TH"],
    startTime: "13:00",
    endTime: "14:20",
    nativeText: "AL 113",
    buildingId: "arts-lecture-hall",
    room: "113",
  },
  {
    courseCode: "CS 135",
    courseName: "Functional Programming Tutorial",
    nativeSection: "T02",
    nativeComponentType: "TUT",
    days: ["TH"],
    startTime: "14:30",
    endTime: "15:20",
    nativeText: "DC 1350",
    buildingId: "william-g-davis-computer-research-centre",
    room: "1350",
  },
]);
