import type { Meeting } from "../common/model";

export const DEMO_WATERLOO_MEETINGS: Meeting[] = [
  {
    id: "demo-waterloo-math135-lec",
    institutionId: "waterloo",
    courseCode: "MATH 135",
    nativeSection: "001",
    nativeComponentType: "LEC",
    courseName: "Algebra for Honours Mathematics",
    termLabel: "Fall 2026",
    days: ["MO", "WE", "FR"],
    startTime: "09:30",
    endTime: "10:20",
    startDate: "2026-09-09",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "MC 2066",
      buildingId: "mathematics-computer-building",
      room: "2066",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-30T12:00:00.000Z" },
  },
  {
    id: "demo-waterloo-cs135-lec",
    institutionId: "waterloo",
    courseCode: "CS 135",
    nativeSection: "002",
    nativeComponentType: "LEC",
    courseName: "Designing Functional Programs",
    termLabel: "Fall 2026",
    days: ["MO", "WE", "FR"],
    startTime: "11:30",
    endTime: "12:20",
    startDate: "2026-09-09",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "DC 1351",
      buildingId: "william-g-davis-computer-research-centre",
      room: "1351",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-30T12:00:00.000Z" },
  },
  {
    id: "demo-waterloo-psych101-lec",
    institutionId: "waterloo",
    courseCode: "PSYCH 101",
    nativeSection: "003",
    nativeComponentType: "LEC",
    courseName: "Introductory Psychology",
    termLabel: "Fall 2026",
    days: ["TU", "TH"],
    startTime: "13:00",
    endTime: "14:20",
    startDate: "2026-09-09",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "AL 113",
      buildingId: "arts-lecture-hall",
      room: "113",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-30T12:00:00.000Z" },
  },
];
