import type { Meeting } from "../common/model";

export const DEMO_UBC_MEETINGS: Meeting[] = [
  {
    id: "demo-ubc-cpsc110-lec",
    institutionId: "ubc",
    courseCode: "CPSC 110",
    nativeSection: "101",
    nativeComponentType: "LEC",
    courseName: "Computation, Programs, and Programming",
    termLabel: "Fall 2026",
    days: ["MO", "WE"],
    startTime: "09:00",
    endTime: "10:00",
    startDate: "2026-09-08",
    endDate: "2026-12-07",
    location: {
      kind: "physical",
      nativeText: "ICCS X836",
      buildingId:
        "institute-for-computing-information-and-cognitive-systems-computer-science-building",
      room: "X836",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-29T12:00:00.000Z" },
  },
  {
    id: "demo-ubc-engl110-lec",
    institutionId: "ubc",
    courseCode: "ENGL 110",
    nativeSection: "002",
    nativeComponentType: "LEC",
    courseName: "Approaches to Literature and Culture",
    termLabel: "Fall 2026",
    days: ["MO", "WE"],
    startTime: "12:00",
    endTime: "13:00",
    startDate: "2026-09-08",
    endDate: "2026-12-07",
    location: {
      kind: "physical",
      nativeText: "BUCH A101",
      buildingId: "buchanan-building",
      room: "A101",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-29T12:00:00.000Z" },
  },
  {
    id: "demo-ubc-phrm100-lec",
    institutionId: "ubc",
    courseCode: "PHRM 100",
    nativeSection: "001",
    nativeComponentType: "LEC",
    courseName: "Foundations of Pharmacy",
    termLabel: "Fall 2026",
    days: ["TU", "TH"],
    startTime: "10:00",
    endTime: "11:30",
    startDate: "2026-09-08",
    endDate: "2026-12-07",
    location: {
      kind: "physical",
      nativeText: "PHRM 1101",
      buildingId: "pharmaceutical-sciences-building",
      room: "1101",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-29T12:00:00.000Z" },
  },
];
